# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='votes',
            new_name='polarity',
        ),
    ]
