# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_auto_20151228_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_text',
            new_name='text',
        ),
    ]
